# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarthageCli < Formula
  desc ""
  homepage "https://github.com/Abdelwaeb-Hnaien/homebrew-carthage-cli"
  version "0.1.3"

  on_macos do
    url "https://github.com/Abdelwaheb-Hnaien/carthage-cli/releases/download/v0.1.3/carthage-cli_0.1.3_darwin_all.tar.gz"
    sha256 "edb0ed5c93898c4120ab0c00b7f0410ade317b39c2d06483de7aed3be1ede8d7"

    def install
      bin.install "carthage-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdelwaheb-Hnaien/carthage-cli/releases/download/v0.1.3/carthage-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "4023c9fef74252a8e6d8ae9dc16f40e9982b746b0d1c6beef4d163b56eb2e53f"

      def install
        bin.install "carthage-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdelwaheb-Hnaien/carthage-cli/releases/download/v0.1.3/carthage-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "bbcb79aab0f4229e5b69e30de4044cc7fdf8532ceb6a2a0185d4b779b4274afc"

      def install
        bin.install "carthage-cli"
      end
    end
  end
end
